version: "1.0"
services:
  #  collector:
  #    container_name: collector
  #    image: otel/opentelemetry-collector-contrib:0.91.0
  #    command:
  #      - --config=/etc/otelcol-contrib/otel-collector.yml
  #    volumes:
  #      - ./docker/collector/otel-collector-config.yml:/etc/otelcol-contrib/otel-collector.yml
  #    restart: always
  #    ports:
  #      - "4317" # OTLP gRPC receiver
  #      - "8888" # Prometheus exporter metrics

  tempo:
    image: grafana/tempo:latest
    command:
      - --config.file=/etc/tempo/tempo.yml
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo/tempo.yml:ro
      - ./tempo-data:/var/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317:4317"  # otlp grpc
      - "4318"  # otlp http
      - "9411"   # zipkin2024-04-23T16:16:57+0000

  prometheus:
    image: prom/prometheus:v2.46.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.1.0
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  artemis:
    image: apache/activemq-artemis:latest
    container_name: artemis
    ports:
      - "61616:61616" # OpenWire
      - "8161:8161"  # Management Console
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    volumes:
      - artemis-data:/var/lib/artemis
volumes:
  artemis-data: